include: package:solid_lints/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.config.dart
    - lib/routes/**.gr.dart
    - lib/**.freezed.dart
    - lib/**.g.dart
    - build/**
  plugins:
    - custom_lint
  errors:
    lines_longer_than_80_chars: ignore


custom_lint:
  rules:
    - avoid_unused_parameters: false
    - cyclomatic_complexity:
      max_complexity: 4
    - function_lines_of_code:
      max_lines: 80
    - avoid_non_null_assertion
    - avoid_global_state
    - avoid_returning_widgets
    - avoid_unnecessary_setstate
    - double_literal_format
    - avoid_unnecessary_type_assertions
    - avoid_debug_print_in_release
    - avoid_using_api:
      severity: info

dart_code_metrics:
  rules:
    - lines_longer_than_x:
        maxLength: 120
        ignoreComments: true
        ignoreUrls: true
