name: color_jumper
description: color_jumper
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ^3.19.3

dependencies:
  bloc: ^9.0.0
  colornames: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.2.4
  injectable: ^2.5.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  solid_lints: ^0.3.1
  splash_master: ^0.0.2

dependency_overrides:
  meta: ^1.17.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/

splash_master:
  color: '#FFFFFF'
  image: 'assets/logo/logo.png'
  ios_content_mode: 'center'
  android_gravity: 'center'
  android_12_and_above:
    color: '#FFFFFF'
    image: 'assets/logo/logo.png'
