name: color_jumper
description: color_jumper
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ^3.19.3

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  go_router: ^15.2.4
  injectable: ^2.5.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  solid_lints: ^0.3.1

dependency_overrides:
  meta: ^1.17.0

flutter:
  uses-material-design: true
  generate: true
